services:
  postgres:
    container_name: tenpodb
    image: postgres
    environment:
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - tenpostack
    restart: unless-stopped
  pgadmin:
    container_name: pgadmintenpo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
      - tenpostack
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - tenpostack
  eureka-server:
    image: fernandodm/eureka-server:1.0-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tenpostack
    depends_on:
      - zipkin
  apigw:
    image: fernandodm/apigw:1.0-SNAPSHOT
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tenpostack
    depends_on:
      - zipkin
      - eureka-server
  apirest:
    image: fernandodm/apirest:1.0-SNAPSHOT
    container_name: apirest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tenpostack
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
  share:
    image: fernandodm/share:1.0-SNAPSHOT
    container_name: share
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tenpostack
      - postgres
    depends_on:
      - zipkin
      - eureka-server

networks:
  postgres:
    driver: bridge
  tenpostack:
    driver: bridge

volumes:
  postgres:
  pgadmin: