#http://localhost:8080/h2-console,
# configurar en consola : jdbc:h2:mem:EntityValue

server:
  port: 8080

spring:
  application:
    name: apirest
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:/Users/constantine/IdeaProjects/katasYEjemplos/tenpostack/dbinmemory/data/tenpo;AUTO_SERVER=true
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
